[phases.setup]
nixPkgs = [
  "R",
  "gcc",
  "zlib.dev",
  "libgit2",
  "openssl.dev",
  "gdal",     # per sf i mapSpain
  "proj",     # per sf i mapSpain
  "geos",     # per sf
  "curl",     # per mapSpain o leaflet
  "pkg-config",  # per compilar paquets amb dependències natives
  "libxml2.dev"  # pot ser necessari per shiny o htmltools
]

[variables]
NIXPACKS_CACHE = "true" # activa la memòria cau per evitar reinstal·lació en cada build

[phases.install]
commands = [
  # Bloc 1: paquets bàsics
  "R -e 'install.packages(c(\"readr\", \"dplyr\", \"htmltools\"), repos=\"https://packagemanager.posit.co/cran/latest\")'",

  # Bloc 2: paquets shiny
  "R -e 'install.packages(c(\"shiny\", \"shinythemes\", \"shinyWidgets\", \"shinyjs\"), repos=\"https://packagemanager.posit.co/cran/latest\")'",

  # Bloc 3: mapes i gràfics
  "R -e 'install.packages(c(\"plotly\", \"leaflet\", \"sf\", \"mapSpain\"), repos=\"https://packagemanager.posit.co/cran/latest\")'"
]

[phases.build]
commands = []

[start]
cmd = "R -e 'shiny::runApp(port=as.numeric(Sys.getenv(\"PORT\")), host=\"0.0.0.0\")'"
