---
title: "hábitos_alimenticios_preprocesamiento"
author: "Eric Farran Moreno"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}
# Librerias
if (!require(readxl)) install.packages("readxl"); library(readxl)
if (!require(dplyr)) install.packages("dplyr"); library(dplyr)
if (!require(tidyr)) install.packages("tidyr"); library(tidyr)
if (!require(stringr)) install.packages("stringr"); library(stringr)
```

```{r}
# Se establecen las comunidades autónomas de Espanya y las categorias de los datos
ccaa <- c("T.ESPAÑA", "Cataluña", "Aragón", "Islas Baleares", "Valenciana, Comunidad", 
            "Murcia, Región de", "Andalucía", "Madrid, Comunidad de", "Castilla-La Mancha", 
            "Extremadura", "Castilla y León", "Galicia", "Asturias, Principado de", 
            "Cantabria", "País Vasco", "La Rioja", "Navarra, Comunidad Foral de", "Canarias")
  
categorias <- c("CONSUMO_X_CAPITA", "GASTO_X_CAPITA", "PENETRACION", "PRECIO_MEDIO", "VALOR", "VOLUMEN")
  
# Se define una función para unificar excels con múltiples hojas
sheet_compact <- function(file, sheet) {
  df <- read_excel(file, sheet = sheet, skip=2)
  colnames(df)[1] <- "alimento"
  colnames(df)[-1] <- paste(rep(ccaa, each = length(categorias)), categorias, sep = "_")
  df_long <- df %>%
    pivot_longer(
      cols = -alimento,
      names_to = c("ccaa", "categoria"),
      names_sep = "_",
      values_to = "valor"
    ) %>%
    mutate(mes = str_to_title(sheet))
  return(df_long);
}

# Se define una función para unificar múltplies excels
file_compact <- function(file) {
  sheets <- excel_sheets(file)[-1]
  dfs <- lapply(sheets, function(sh) sheet_compact(file, sh))
  df <- bind_rows(dfs) %>%
      mutate(any = tools::file_path_sans_ext(basename(file)))
  df_final <- df[, c("any", "mes", "ccaa", "alimento", "categoria", "valor")] %>%
    arrange(any, mes, ccaa, alimento, categoria)
  colnames(df_final)[1] <- "año"
  return(df_final);
}

row_compact <- function(df, col) {
  k <- 1
  df_final <- df
  remove <- integer(0)
  for (i in df[[col]]) {
    if (i == "TOTAL LECHE LIQUIDA") {
      df_final[["valor"]][k] <- df[["valor"]][k] + df[["valor"]][k+1]
      remove <- c(remove, k+1)
    }
    k <- k+1
  }
  df_final <- df_final[-remove,]
  return(df_final)
}

pyramid_classifier <- function(alimentos) {
  alimento <- toupper(alimentos)
  list <- character(length(alimento))
  for (pos in seq_along(alimento)) {
    a <- alimento[pos]
    
    if (grepl("PAN|AGUA|ARROZ|PASTA|PATATAS|LEGUMBRE", a)) {
      list[pos] <- "1"
    }
    
    else if (grepl("FRUTAS|HORTALIZAS|ACEITE", a)) {
      list[pos] <- "2"
    }
    
    # 2a Nivel: Lácteos y proteínas saludables
    else if (grepl("PESCA|FRUTOS|LECHE|HUEVOS", a)) {
      list[pos] <- "3"
    }
    
    else if (grepl("CARNE", a)) {
      list[pos] <- "4"
    }
    
    # 4to Cima: Ultraprocesados y azúcares
    else if (grepl("AZUCAR|VINOS|CERVEZA|ZUMO|PREPARADOS|MIEL", a)) {
      list[pos] <- "5"
    }
    
    else {
      list[pos] <- NA
    }
  }
  factor(list, levels = c("1", "2", "3", "4", "5"), ordered = TRUE)
}

# Se construye una función para exportar los datos a un csv
get_data <- function(xlsx, f, final_path) {
  files <- file.path("data", xlsx)
  lapply(files, f) %>%
    bind_rows() %>%
    subset(subset = categoria == "VOLUMEN" &
             grepl("\\bTOTAL\\b|\\bMIEL\\b|^PAN$|^ARROZ$\\b|\\bAZUCAR\\b|^LEGUMBRES$|\\bCERVEZAS\\b|\\bT\\.HORTALIZAS\\b|\\bT\\.FRUTAS FRESCAS\\b|^FRUTOS SECOS$|\\bPLATOS PREPARADOS\\b|\\bAGUA DE BEBIDA ENVAS\\.\\b", alimento) &
             !grepl(".TOTAL ALIMENTACION|OLIVA", alimento),
           select = -categoria) %>%
    row_compact("alimento") %>%
    mutate(
      alimento = recode(alimento, "TOTAL LECHE LIQUIDA" = "TOTAL LECHE"),
      nivel = pyramid_classifier(alimento),
      valor = as.numeric(valor),
      valor = round(valor, 2)
    ) %>%
    rename("volumen" = "valor") %>%
    subset(subset = ccaa != "T.ESPAÑA",
           select = -alimento) %>%
    group_by(año, mes, ccaa, nivel) %>%
    summarise(volumen = sum(volumen, na.rm = TRUE)) %>%
    arrange(año, mes, ccaa, nivel) %>%
    write.csv(final_path)
    
  print("Done.")
}
```

```{r echo=FALSE, message=FALSE}
# Se citan los archivos excel i se ejecuta file_compact
xlsx <- c("2014.xlsx",
          "2015.xlsx",
          "2016.xlsx",
          "2017.xlsx",
          "2018.xlsx",
          "2019.xlsx",
          "2020.xlsx",
          "2021.xlsx",
          "2022.xlsx",
          "2023.xlsx")
get_data(xlsx,
         file_compact,
         "data/hábitos_alimenticios_España.csv")
```

